# Generated by Django 5.0.2 on 2024-03-02 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_app', '0001_initial'),
        ('members_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users_enrolled',
            field=models.ManyToManyField(related_name='enrolled_courses', through='members_app.UserEnrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
