# Generated by Django 5.0.2 on 2024-03-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_courses_remove_course_users_enrolled'),
        ('members_app', '0002_userenrollments_delete_userenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='enrollments',
            field=models.ManyToManyField(to='members_app.userenrollments'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
